trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm test
  displayName: 'npm install and build and test'
 



- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    Contents: |
      '/home/vsts/work/1/s/catalog-api/package.json' 
      '/home/vsts/work/1/s/catalog-api/app.js'
      '/home/vsts/work/1/s/catalog-api/bin/*' 
      '/home/vsts/work/1/s/catalog-api/routes/*' 
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish npm artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/npm
    ArtifactName: 'npm'
    publishLocation: 'Container'